services:
  bot:
    image: goodsocd:latest
    restart: unless-stopped
    volumes:
      - goodsocd_data:/data
    environment:
      - TELEGO_BOT_TOKEN=${TELEGO_BOT_TOKEN}
      - PATH_TO_DB=/data/counter.db

volumes:
  goodsocd_data:
